package com.example.aigenerator.data

import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.PropertyName

// Use default values for Firebase deserialization
data class Prompt(
    @DocumentId val id: String = "",          // Holds the Auto-ID generated by Firebase
    val Text: String = "",                   // Matches the 'text' field in Firestore
    val category: String = ""                // Matches the 'category' field in Firestore
)